FORMAT: 1A

# Nee-co API Document

<!-- include(cuenta.md) -->
<!-- include(cadena.md) -->
<!-- include(aldea.md) -->
<!-- include(caja.md) -->
<!-- include(bandeja.md) -->
<!-- include(imagen.md) -->
<!-- include(olvido.md) -->
